apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: innomaux-com-tls
spec:
  secretName: innomaux-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: innomaux-com
  dnsNames:
    - innomaux.com
    - www.innomaux.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - innomaux.com
          - www.innomaux.com
      